// <auto-generated />
namespace contact_management.web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addNotes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addNotes));
        
        string IMigrationMetadata.Id
        {
            get { return "201601061331365_addNotes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
